version: "3.8"

services:
  backend:
    build: .
    ports:
      - "8000:8000"  # Map container port to host
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/processed:/app/processed
    stdin_open: true
    tty: true